# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:18
from __future__ import unicode_literals

import addrreg.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Object ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('houseNumber', models.CharField(blank=True, max_length=255, verbose_name='House Number')),
                ('floor', models.CharField(blank=True, max_length=255, verbose_name='Floor')),
                ('door', models.CharField(blank=True, max_length=255, verbose_name='Door')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ('road',),
            },
        ),
        migrations.CreateModel(
            name='AddressRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('houseNumber', models.CharField(blank=True, max_length=255, verbose_name='House Number')),
                ('floor', models.CharField(blank=True, max_length=255, verbose_name='Floor')),
                ('door', models.CharField(blank=True, max_length=255, verbose_name='Door')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Object ID')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
                ('registration_to', models.DateTimeField(db_index=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('road',),
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addrreg_address_registrations',
            },
        ),
        migrations.CreateModel(
            name='BNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Object ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('number', models.CharField(db_index=True, max_length=255, verbose_name='Number')),
                ('name', models.CharField(max_length=255, verbose_name='Nickname')),
                ('block', models.CharField(max_length=255, verbose_name='Block Designation')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'B-Number',
                'verbose_name_plural': 'B-Numbers',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='BNumberRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('number', models.CharField(db_index=True, max_length=255, verbose_name='Number')),
                ('name', models.CharField(max_length=255, verbose_name='Nickname')),
                ('block', models.CharField(max_length=255, verbose_name='Block Designation')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Object ID')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
                ('registration_to', models.DateTimeField(db_index=True, editable=False, null=True)),
            ],
            options={
                'ordering': ('number',),
                'verbose_name': 'B-Number',
                'verbose_name_plural': 'B-Numbers',
                'db_table': 'addrreg_bnumber_registrations',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Object ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('code', models.IntegerField(db_index=True, unique=True, verbose_name='Code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('type', enumfields.fields.EnumIntegerField(db_index=True, default=0, enum=addrreg.models.LocalityType, verbose_name='Type')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LocalityRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('type', enumfields.fields.EnumIntegerField(db_index=True, default=0, enum=addrreg.models.LocalityType, verbose_name='Type')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Object ID')),
                ('code', models.IntegerField(db_index=True, verbose_name='Code')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
                ('registration_to', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.Locality')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
                'db_table': 'addrreg_locality_registrations',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Object ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('code', models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MunicipalityRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Object ID')),
                ('code', models.PositiveSmallIntegerField(db_index=True, verbose_name='Code')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
                ('registration_to', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.Municipality')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'db_table': 'addrreg_municipality_registrations',
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Object ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('code', models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='Number')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='City')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Postal Code',
                'verbose_name_plural': 'Postal Codes',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='PostalCodeRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='City')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Object ID')),
                ('code', models.PositiveSmallIntegerField(db_index=True, verbose_name='Number')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
                ('registration_to', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.PostalCode')),
            ],
            options={
                'ordering': ('code',),
                'verbose_name': 'Postal Code',
                'verbose_name_plural': 'Postal Codes',
                'db_table': 'addrreg_postalcode_registrations',
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Object ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('code', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('shortname', models.CharField(max_length=20, verbose_name='Abbreviated Name')),
                ('dkName', models.CharField(max_length=255, verbose_name='Danish Name')),
                ('glName', models.CharField(max_length=255, verbose_name='Greenlandic Name')),
                ('cprName', models.CharField(max_length=255, verbose_name='CPR Name')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Road',
                'verbose_name_plural': 'Roads',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RoadRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('shortname', models.CharField(max_length=20, verbose_name='Abbreviated Name')),
                ('dkName', models.CharField(max_length=255, verbose_name='Danish Name')),
                ('glName', models.CharField(max_length=255, verbose_name='Greenlandic Name')),
                ('cprName', models.CharField(max_length=255, verbose_name='CPR Name')),
                ('objectID', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Object ID')),
                ('code', models.PositiveIntegerField(db_index=True, verbose_name='Code')),
                ('registration_from', models.DateTimeField(db_index=True, editable=False)),
                ('registration_to', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.Road')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Road',
                'verbose_name_plural': 'Roads',
                'db_table': 'addrreg_road_registrations',
            },
        ),
        migrations.AddField(
            model_name='bnumberregistrations',
            name='municipality',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='addrreg.Municipality', verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='bnumberregistrations',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.BNumber'),
        ),
        migrations.AddField(
            model_name='bnumber',
            name='municipality',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='addrreg.Municipality', verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='addressregistrations',
            name='bNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addrreg.BNumber', verbose_name='B-Number'),
        ),
        migrations.AddField(
            model_name='addressregistrations',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addrreg.Locality', verbose_name='Locality'),
        ),
        migrations.AddField(
            model_name='addressregistrations',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.Address'),
        ),
        migrations.AddField(
            model_name='addressregistrations',
            name='postalCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='addrreg.PostalCode', verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='addressregistrations',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addrreg.Road', verbose_name='Road'),
        ),
        migrations.AddField(
            model_name='address',
            name='bNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addrreg.BNumber', verbose_name='B-Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addrreg.Locality', verbose_name='Locality'),
        ),
        migrations.AddField(
            model_name='address',
            name='postalCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='addrreg.PostalCode', verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='address',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addrreg.Road', verbose_name='Road'),
        ),
        migrations.AlterIndexTogether(
            name='roadregistrations',
            index_together=set([('object', 'registration_from', 'registration_to'), ('objectID', 'registration_from', 'registration_to')]),
        ),
        migrations.AlterIndexTogether(
            name='postalcoderegistrations',
            index_together=set([('object', 'registration_from', 'registration_to'), ('objectID', 'registration_from', 'registration_to')]),
        ),
        migrations.AlterIndexTogether(
            name='municipalityregistrations',
            index_together=set([('object', 'registration_from', 'registration_to'), ('objectID', 'registration_from', 'registration_to')]),
        ),
        migrations.AlterIndexTogether(
            name='localityregistrations',
            index_together=set([('object', 'registration_from', 'registration_to'), ('objectID', 'registration_from', 'registration_to')]),
        ),
        migrations.AlterIndexTogether(
            name='bnumberregistrations',
            index_together=set([('object', 'registration_from', 'registration_to'), ('objectID', 'registration_from', 'registration_to')]),
        ),
        migrations.AlterIndexTogether(
            name='addressregistrations',
            index_together=set([('object', 'registration_from', 'registration_to'), ('objectID', 'registration_from', 'registration_to')]),
        ),
    ]
