# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('objectID', models.UUIDField(primary_key=True, serialize=False)),
                ('houseNumber', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BNumber',
            fields=[
                ('objectID', models.UUIDField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('objectID', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('objectID', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('objectID', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('objectID', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=20)),
                ('dkName', models.CharField(max_length=255)),
                ('glName', models.CharField(max_length=255)),
                ('cprName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bnumber',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addrreg.Municipality'),
        ),
        migrations.AddField(
            model_name='address',
            name='bNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addrreg.BNumber'),
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addrreg.Locality'),
        ),
        migrations.AddField(
            model_name='address',
            name='postalCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addrreg.PostalCode'),
        ),
        migrations.AddField(
            model_name='address',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addrreg.Road'),
        ),
    ]
