# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressregistrations',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stateregistrations',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='addressregistrations',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='bnumberregistrations',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='districtregistrations',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='localityregistrations',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='municipalityregistrations',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='postalcoderegistrations',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='roadregistrations',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='stateregistrations',
            unique_together=set([]),
        ),
    ]
