# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0001_initial_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stateregistrations',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Name'),
        ),
    ]
