# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 12:34
from __future__ import unicode_literals

import addrreg.models.base
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/address/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/address/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='code',
            field=models.CharField(db_index=True, max_length=8, null=True, verbose_name='B-Number'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/number/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='code',
            field=models.CharField(db_index=True, max_length=8, null=True, verbose_name='B-Number'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/number/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='district',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='district',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/district/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/district/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/locality/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/locality/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/municipality/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/municipality/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/postalcode/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/postalcode/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='road',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='Alternate Name'),
        ),
        migrations.AlterField(
            model_name='road',
            name='cpr_name',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='CPR Name'),
        ),
        migrations.AlterField(
            model_name='road',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='road',
            name='shortname',
            field=models.CharField(blank=True, help_text='20 character maximum', max_length=20, null=True, verbose_name='Abbreviated Name'),
        ),
        migrations.AlterField(
            model_name='road',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='road',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/road/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='Alternate Name'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='cpr_name',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='CPR Name'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='shortname',
            field=models.CharField(blank=True, help_text='20 character maximum', max_length=20, null=True, verbose_name='Abbreviated Name'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='state',
            field=models.ForeignKey(default=addrreg.models.base._default_state, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='addrreg.State', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/road/v1', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='state',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='stateregistrations',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
    ]
