# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0002_drop_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='shortname',
            field=models.CharField(help_text='20 character maximum', max_length=20, null=True, verbose_name='Abbreviated Name'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='shortname',
            field=models.CharField(help_text='20 character maximum', max_length=20, null=True, verbose_name='Abbreviated Name'),
        ),
    ]
