# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:13
from __future__ import unicode_literals

import addrreg.models.base
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0003_bnumber_renames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/address', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/address', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/number', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/number', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='district',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/district', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/district', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/locality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/locality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/municipality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/municipality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/postalcode', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/postalcode', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='road',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/road', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='sumiiffik_domain',
            field=addrreg.models.base.SumiiffikDomainField(default='https://data.gl/najugaq/road', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiiffik Domain'),
        ),
    ]
