# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 08:00
from __future__ import unicode_literals

import addrreg.models.base
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0003_shortname_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='b_number',
            field=addrreg.models.base.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addrreg.BNumber', verbose_name='B-Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=addrreg.models.base.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addrreg.Municipality', verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='address',
            name='road',
            field=addrreg.models.base.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addrreg.Road', verbose_name='Road'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='b_number',
            field=addrreg.models.base.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addrreg.BNumber', verbose_name='B-Number'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='municipality',
            field=addrreg.models.base.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addrreg.Municipality', verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='road',
            field=addrreg.models.base.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addrreg.Road', verbose_name='Road'),
        ),
    ]
