# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0004_sumiiffik_domain_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressregistrations',
            options={'default_permissions': (), 'ordering': ('road',), 'verbose_name': 'Registrering for Adresse', 'verbose_name_plural': 'Registreringer for Adresse'},
        ),
        migrations.AlterModelOptions(
            name='bnumberregistrations',
            options={'default_permissions': (), 'verbose_name': 'Registrering for B-nummer', 'verbose_name_plural': 'Registreringer for B-nummer'},
        ),
        migrations.AlterModelOptions(
            name='districtregistrations',
            options={'default_permissions': (), 'ordering': ('abbrev',), 'verbose_name': 'Registrering for Distrikt', 'verbose_name_plural': 'Registreringer for Distrikt'},
        ),
        migrations.AlterModelOptions(
            name='localityregistrations',
            options={'default_permissions': (), 'ordering': ('abbrev',), 'verbose_name': 'Registrering for Lokalitet', 'verbose_name_plural': 'Registreringer for Lokalitet'},
        ),
        migrations.AlterModelOptions(
            name='municipalityregistrations',
            options={'default_permissions': (), 'ordering': ('abbrev',), 'verbose_name': 'Registrering for Kommune', 'verbose_name_plural': 'Registreringer for Kommune'},
        ),
        migrations.AlterModelOptions(
            name='postalcoderegistrations',
            options={'default_permissions': (), 'ordering': ('code',), 'verbose_name': 'Registrering for Postnummer', 'verbose_name_plural': 'Registreringer for Postnummer'},
        ),
        migrations.AlterModelOptions(
            name='roadregistrations',
            options={'default_permissions': (), 'ordering': ('name',), 'verbose_name': 'Registrering for Vej', 'verbose_name_plural': 'Registreringer for Vej'},
        ),
        migrations.AlterModelOptions(
            name='stateregistrations',
            options={'default_permissions': (), 'ordering': ('code',), 'verbose_name': 'Registrering for Tilstand', 'verbose_name_plural': 'Registreringer for Tilstand'},
        ),
        migrations.AlterField(
            model_name='address',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration Time'),
        ),
        migrations.AlterField(
            model_name='address',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='address',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='checksum',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.Address', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='registration_to',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='registration_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration Time'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='checksum',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.BNumber', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='registration_to',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='registration_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='district',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration Time'),
        ),
        migrations.AlterField(
            model_name='district',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='district',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='checksum',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.District', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='registration_to',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='registration_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration Time'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='checksum',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.Locality', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='registration_to',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='registration_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration Time'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='checksum',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.Municipality', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='registration_to',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='registration_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration Time'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='checksum',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.PostalCode', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='registration_to',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='registration_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='road',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration Time'),
        ),
        migrations.AlterField(
            model_name='road',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='road',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='checksum',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.Road', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='registration_to',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='registration_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='state',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration Time'),
        ),
        migrations.AlterField(
            model_name='state',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='state',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
        migrations.AlterField(
            model_name='stateregistrations',
            name='checksum',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='stateregistrations',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='addrreg.State', verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='stateregistrations',
            name='registration_from',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='stateregistrations',
            name='registration_to',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='Registration From'),
        ),
        migrations.AlterField(
            model_name='stateregistrations',
            name='registration_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='stateregistrations',
            name='valid_from',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='stateregistrations',
            name='valid_to',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Valid To'),
        ),
    ]
