# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 08:42
from __future__ import unicode_literals

import addrreg.models.base
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0005_adjust-field-labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressregistrations',
            options={'default_permissions': (), 'ordering': ('road',), 'verbose_name': 'Address Registration', 'verbose_name_plural': 'Address Registrations'},
        ),
        migrations.AlterModelOptions(
            name='bnumberregistrations',
            options={'default_permissions': (), 'verbose_name': 'B-Number Registration', 'verbose_name_plural': 'B-Number Registrations'},
        ),
        migrations.AlterModelOptions(
            name='districtregistrations',
            options={'default_permissions': (), 'ordering': ('abbrev',), 'verbose_name': 'District Registration', 'verbose_name_plural': 'District Registrations'},
        ),
        migrations.AlterModelOptions(
            name='localityregistrations',
            options={'default_permissions': (), 'ordering': ('abbrev',), 'verbose_name': 'Locality Registration', 'verbose_name_plural': 'Locality Registrations'},
        ),
        migrations.AlterModelOptions(
            name='municipalityregistrations',
            options={'default_permissions': (), 'ordering': ('abbrev',), 'verbose_name': 'Municipality Registration', 'verbose_name_plural': 'Municipality Registrations'},
        ),
        migrations.AlterModelOptions(
            name='postalcoderegistrations',
            options={'default_permissions': (), 'ordering': ('code',), 'verbose_name': 'Postal Code Registration', 'verbose_name_plural': 'Postal Code Registrations'},
        ),
        migrations.AlterModelOptions(
            name='roadregistrations',
            options={'default_permissions': (), 'ordering': ('name',), 'verbose_name': 'Road Registration', 'verbose_name_plural': 'Road Registrations'},
        ),
        migrations.AlterModelOptions(
            name='stateregistrations',
            options={'default_permissions': (), 'ordering': ('code',), 'verbose_name': 'State Registration', 'verbose_name_plural': 'State Registrations'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='address',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='addressregistrations',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='addressregistrations',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='bnumber',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='bnumber',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='bnumberregistrations',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='bnumberregistrations',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='district',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='district',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='districtregistrations',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='districtregistrations',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='localityregistrations',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='localityregistrations',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='municipalityregistrations',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='municipalityregistrations',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='postalcode',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='postalcode',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='postalcoderegistrations',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='postalcoderegistrations',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='road',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='road',
            name='sumiiffik_domain',
        ),
        migrations.RemoveField(
            model_name='roadregistrations',
            name='sumiiffik',
        ),
        migrations.RemoveField(
            model_name='roadregistrations',
            name='sumiiffik_domain',
        ),
        migrations.AddField(
            model_name='address',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='address',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/address', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='addressregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='addressregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/address', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='bnumber',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='bnumber',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/number', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='bnumberregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='bnumberregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/number', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='district',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='district',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/district', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='districtregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='districtregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/district', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='locality',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='locality',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/locality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='localityregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='localityregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/locality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, null=True, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/municipality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='municipalityregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, null=True, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='municipalityregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/municipality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/postalcode', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='postalcoderegistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='postalcoderegistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/postalcode', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='road',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='road',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/road', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AddField(
            model_name='roadregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AddField(
            model_name='roadregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/road', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
    ]
