# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-14 14:41
from __future__ import unicode_literals

import addrreg.models.base
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0005_adjust-field-labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='addressregistrations',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='addressregistrations',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='bnumber',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='bnumber',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='bnumberregistrations',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='bnumberregistrations',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='districtregistrations',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='districtregistrations',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='locality',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='locality',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='localityregistrations',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='localityregistrations',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='municipalityregistrations',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='municipalityregistrations',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='postalcode',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='postalcode',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='postalcoderegistrations',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='postalcoderegistrations',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='road',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.RenameField(
            model_name='roadregistrations',
            old_name='sumiiffik',
            new_name='sumiffiik',
        ),
        migrations.RenameField(
            model_name='roadregistrations',
            old_name='sumiiffik_domain',
            new_name='sumiffiik_domain',
        ),
        migrations.AlterField(
            model_name='address',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/address', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='addressregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/address', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='bnumber',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/number', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='bnumberregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/number', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='district',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='district',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/district', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='districtregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/district', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/locality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='localityregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/locality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, null=True, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/municipality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, null=True, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='municipalityregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/municipality', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/postalcode', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='postalcoderegistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/postalcode', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='road',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='road',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/road', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='sumiffiik',
            field=addrreg.models.base.SumiffiikIDField(db_index=True, default=addrreg.models.base._random_sumiffiik, max_length=38, verbose_name='Sumiffiik ID'),
        ),
        migrations.AlterField(
            model_name='roadregistrations',
            name='sumiffiik_domain',
            field=addrreg.models.base.SumiffiikDomainField(default='https://data.gl/najugaq/road', max_length=64, validators=[django.core.validators.URLValidator()], verbose_name='Sumiffiik Domain'),
        ),
    ]
