# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0006_auto_20170920_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressregistrations',
            options={'default_permissions': (), 'ordering': ('road',), 'verbose_name': 'Registrering for Adresse', 'verbose_name_plural': 'Registreringer for Adresse'},
        ),
        migrations.AlterModelOptions(
            name='bnumberregistrations',
            options={'default_permissions': (), 'verbose_name': 'Registrering for B-nummer', 'verbose_name_plural': 'Registreringer for B-nummer'},
        ),
        migrations.AlterModelOptions(
            name='districtregistrations',
            options={'default_permissions': (), 'ordering': ('abbrev',), 'verbose_name': 'Registrering for Distrikt', 'verbose_name_plural': 'Registreringer for Distrikt'},
        ),
        migrations.AlterModelOptions(
            name='localityregistrations',
            options={'default_permissions': (), 'ordering': ('abbrev',), 'verbose_name': 'Registrering for Lokalitet', 'verbose_name_plural': 'Registreringer for Lokalitet'},
        ),
        migrations.AlterModelOptions(
            name='municipalityregistrations',
            options={'default_permissions': (), 'ordering': ('abbrev',), 'verbose_name': 'Registrering for Kommune', 'verbose_name_plural': 'Registreringer for Kommune'},
        ),
        migrations.AlterModelOptions(
            name='postalcoderegistrations',
            options={'default_permissions': (), 'ordering': ('code',), 'verbose_name': 'Registrering for Postnummer', 'verbose_name_plural': 'Registreringer for Postnummer'},
        ),
        migrations.AlterModelOptions(
            name='roadregistrations',
            options={'default_permissions': (), 'ordering': ('name',), 'verbose_name': 'Registrering for Vej', 'verbose_name_plural': 'Registreringer for Vej'},
        ),
        migrations.AlterModelOptions(
            name='stateregistrations',
            options={'default_permissions': (), 'ordering': ('code',), 'verbose_name': 'Registrering for Tilstand', 'verbose_name_plural': 'Registreringer for Tilstand'},
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='Code'),
        ),
    ]
