# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addrreg', '0006_fix_sumiiffik_spelling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='receipt_errorcode',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
